// <auto-generated />
using LaLiga.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaLiga.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogContext))]
    partial class CatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaLiga.Domain.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Technology",
                            Description = "Everything in technology"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "T-Shirts",
                            Description = "Fashion for all teams"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Hoodie",
                            Description = "Hoodie relaxing fit XCH"
                        });
                });

            modelBuilder.Entity("LaLiga.Domain.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Apple Watch",
                            Stock = 60,
                            UnitPrice = 1600000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Madrid T-Shirt",
                            Stock = 140,
                            UnitPrice = 600000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Name = "Looney Toons",
                            Stock = 50,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "IPhone 12",
                            Stock = 80,
                            UnitPrice = 3400000m
                        });
                });

            modelBuilder.Entity("LaLiga.Domain.Model.Product", b =>
                {
                    b.HasOne("LaLiga.Domain.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
